version: '3.8'

services:
  postgres:
    image: postgres:17.2
    container_name: devices-postgres
    environment:
      POSTGRES_DB: devices
      POSTGRES_USER: devices
      POSTGRES_PASSWORD: devices
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devices"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devices-network


volumes:
  postgres_data:

networks:
  devices-network:
    driver: bridge

